### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by ntutchton** [JacyAnderson/project-3#85]
As a user I found myself looking for a back button on the page instead of the back button in my browser... May want to add one if possible.  If I click 'happy' and then decide-- no wait im sad-- a back button would be nice

**Comment by tlaine1441** [comment]
I really like this one!!!

**Comment by ntutchton** [comment]
I really want the escape button to delete my browser history.  I don't think this is possbile but if I escape and then retrieve the page through my history I end up back at the website AND at the resources pane '../violated'.  Maybe there is a way you could force any traffic to the site to redirect to the home page, so at least when I return to the page the results of the conversation are lost/private.
